# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brev < Formula
  desc "CLI tool for managing workspaces provided by brev.dev"
  homepage "https://docs.brev.dev"
  version "0.6.36-betab"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.36-betab/brev-cli_0.6.36-betab_darwin_amd64.tar.gz"
      sha256 "5f07bc29f552382735236b370154dbb3fc4dbbf96c620ccdcfcee24f2b873bbf"
    end
    if Hardware::CPU.arm?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.36-betab/brev-cli_0.6.36-betab_darwin_arm64.tar.gz"
      sha256 "202772f2c889a53373ddcf9711056dbff6068f8184505b9a38bf6ee5ea4a4f94"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.36-betab/brev-cli_0.6.36-betab_linux_amd64.tar.gz"
      sha256 "3e8863b6c7d0aa9e4bad0b0fa210444c553e90b36453412c1803306c25e46943"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.36-betab/brev-cli_0.6.36-betab_linux_arm64.tar.gz"
      sha256 "e8c42cdaefb513ffc7c354699dd34179a62b571cf7bc01c507e414f36b5391a6"
    end
  end

  def install
    bin.install "brev"
  end

  test do
    system "#{bin}/brev" "--version"
  end
end
