# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Brev < Formula
  desc "CLI tool for managing workspaces provided by brev.dev"
  homepage "https://docs.brev.dev"
  version "0.6.207"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.207/brev-cli_0.6.207_darwin_arm64.tar.gz"
      sha256 "6f29c1a652c3ad7af74f2c58d1661215e2478ef22e4b1777b14ac54ee33ee073"

      def install
        bin.install "brev"
        generate_completions_from_executable("#{bin}/brev", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.207/brev-cli_0.6.207_darwin_amd64.tar.gz"
      sha256 "15ef32b1e771a50f14e4688f526730700b3d18fef328c8a7422b234e7d995db7"

      def install
        bin.install "brev"
        generate_completions_from_executable("#{bin}/brev", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.207/brev-cli_0.6.207_linux_arm64.tar.gz"
      sha256 "0ff0ed82b9ef276a42fc5f2f11a273ac4ee70a5ec0607ec530c21f72eeb87d44"

      def install
        bin.install "brev"
        generate_completions_from_executable("#{bin}/brev", "completion")
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/brevdev/brev-cli/releases/download/v0.6.207/brev-cli_0.6.207_linux_amd64.tar.gz"
      sha256 "8789d9f2967fa6f65c31c391b126b3b2ccf01c2c78c6d0023520edeb057a7284"

      def install
        bin.install "brev"
        generate_completions_from_executable("#{bin}/brev", "completion")
      end
    end
  end

  test do
    system "#{bin}/brev" "--version"
  end
end
